### ISSUE TITLE
Medición automática

### ISSUE THREAD

**Issue by antonio-fiol** [antonio-fiol/tren#11]

**Comment by antonio-fiol** [comment]
Progreso moderado.

Se puede definir en la configuración una `PistaMedicion([ tramo, ... ])`, y existen dos procesos de medicion por pasos, uno para determinar el minimo y otro para determinar la curva.

De momento, debería funcionar la ejecución de los procesos, pero no se ajustan los parámetros del tren, ni existe ningún mecanismo de feedback para ver que el proceso haya funcionado correctamente, aparte del propio log.

**Comment by antonio-fiol** [comment]
@alhnelson cuando puedas me gustaría que hagas alguna prueba del proceso de medición automática, De momento es todo un poco "oscuro", pero la idea es ver si el proceso se completa correctamente, y si es así, ya seguiré avanzando con el resto (incluirlo en la interfaz, hacer que te informe del resultado, etc.).

## Pre-requisitos:
Mientras no esté completo, el código para resolver esta mejora está en la rama "issue-11".
`git checkout issue-11` para cambiar al código de esta rama, y `git checkout master` para volver a la rama principal (eliminando también lo que se añade en el apartado "Configuración".

## Configuración:
`PistaMedicion(tramos=[tramos[x] for x in ["E1",...,"E5","E6"]])`
o
`PistaMedicion(tramos=[tramos["E1"],...,tramos["E5"],tramos["E6"]])`

## Cómo medir:

1. Colocar un tren en algún punto de la pista de medición.
2. En una ventana nueva, llamar a la URL:  `http://host:puerto/tren?medir=true&id=NNN`

## El proceso:
### Medición del mínimo
1. Inicialmente, se comprueba que hay un tren en la pista y no más. Se reservan todos los desvíos que permiten que la pista de medición no se vea afectada por la circulación en el resto de la maqueta. Y se "anulan" los límites de velocidad en la pista. La medición puede empezar.
2. Empieza la medición del mínimo. Inicialmente asumimos que la velocidad mínima del tren estará entre 0 y 100 (no se puede ser más genérico).
3. El tren avanzará a máxima velocidad hasta encontrar un cambio de tramo.
4. Al pasar un cambio de vía o ver que no ha pasado en un cierto tiempo, se ajustará el extremo adecuado del rango de velocidades de trabajo y se decidirá una nueva velocidad de prueba.
5. Si el rango de trabajo es suficientemente pequeño, sabemos ya cuál es el mínimo al que puede trabajar este tren, y el proceso finaliza.
6. El tren retrocede (siempre a velocidad máxima) hasta pasar al tramo anterior.
7. El tren avanzará hasta pasar al tramo siguiente, a la nueva velocidad de prueba.
8. Vuelta al paso 4.

### Medición de la curva
1. El tren empieza circulando a velocidad máxima.
2. Cada 12 cambios de tramo, el tren reduce la velocidad.
3. La curva se va ajustando igual que cuando se realiza la medición de un tren manualmente.

**Comment by alhnelson** [comment]
Me hace un montón de ilusión bajar la maqueta y probar todas estas
novedades.
Pero de momento va a ser imposible hasta que mejore un poco la tendinitis.
Ahora me dedico a cosas más sencillas como hacer fotos o vídeos.

A ver si de una vez por todas puedo seguir con mis hobbys.

Saludos.

Salutacions,
Miquel.

**Comment by antonio-fiol** [comment]
Nuevo commit facilitando las pruebas y con alguna otra mejora. Aún falta que te informe de los resultados de la prueba.

### Cómo medir:

1. Colocar un tren en algún punto de la pista de medición.
2. Desde la rueda de opciones del tren, pulsar "Iniciar medida"

**Comment by antonio-fiol** [comment]
Está probado e integrado en "master". Ya no es necesario descargar la rama issue-11.
