### ISSUE TITLE
Se solapan las locuciones de las estaciones

### ISSUE THREAD

**Issue by antonio-fiol** [antonio-fiol/tren#12]
Al ver el vídeo de @alhnelson  en https://youtu.be/JzZFZZ0UBEc me he dado cuenta de que pueden suceder dos locuciones en la misma estación al mismo tiempo.  Debería intentar evitarse.

 Asimismo, al solaparse locuciones de dos estaciones diferentes, también se produce cierta confusión. Quizá valga la pena explorar la posibilidad de utilizar dos voces diferentes.

**Comment by alhnelson** [comment]
También lo había visto. Hay que decidir si dar dos voces diferentes o
simplemente anular la segunda. También te comenté que según el tiempo de
parada en la estación la locución debería empezar un poco más tarde ya que
no debería reproducirse justo cuando llega el tren.

Por ejemplo:

time:= tiempo_parada-duración_locución+5;
procedure(locución,time);


Salutacions,
Miquel.

**Comment by antonio-fiol** [comment]
Eso de retrasar el evento ya lo tienes con "tras". Revisa issues anteriores
(cerradas).

**Comment by antonio-fiol** [comment]
libttspico solo proporciona una voz por idioma, así que no es factible usar voces distintas sin cambiar el motor de TTS (y ya escogí libttspico porque me pareció el más natural, después de descartar otros).
Revisaré la posibilidad de evitar el solape.

**Comment by alhnelson** [comment]
Perfecto. Creo que la mejor opción es que suene la primera locución evitado
así que se solapen.
Por cierto. Las locuciones se ejecutan en todos los altavoces o sólo en el
altavoz más cercano a la estación?

Salutacions,
Miquel.

**Comment by antonio-fiol** [comment]
Suena en el del tren correspondiente (para evitar tener que indicar que
altavoces corresponden a la estacion)

**Comment by antonio-fiol** [comment]
Puedes probar el intento de solución en la rama issue-12. Para ello:
`git checkout issue-12`

y rodeando el suscriptor del evento con DescartarConcurrencia(suscriptor). Por ejemplo:
`SonidoEstacion("...").cuando...`
pasa a ser:
`DescartarConcurrencia(SonidoEstacion("...")).cuando...`

Para volver atrás, deshacer el cambio en la configuración y usar:
`git checkout master`

**Comment by antonio-fiol** [comment]
Esta funcionalidad ya se ha incorporado a la rama master.
