### ISSUE TITLE
Añadir parámetro del tiempo de activación en los desvíos

### ISSUE THREAD

**Issue by alhnelson** [antonio-fiol/tren#3]
En H0 tengo muchos desvíos no motorizados lo que implica que para ser utilizados es necesario algún todo de mecanismo capaz de mover el desvío en las dos posiciones. Veo que con el sistema que estoy utilizando resulta corto el tiempo que se envía corriente a ambos bobinados.
Sería posible para cada desvío indicar ese tiempo mediante un parámetro adicional y dejando por defecto el que ahora hay si no se indica nada?

**Comment by antonio-fiol** [comment]
Puedo implementar fácilmente algo así

`Desvio(1, inv=False, estado_inicial=Desvio.VERDE, duracion_pulso=0.1)`

Hay que tener en cuenta que mientras está cambiando un desvío, el mundo se para (no se hace detección ni ajustes de velocidad ni nada).
