### ISSUE TITLE
Poner imagen locomotora en el círculo de control

### ISSUE THREAD

**Issue by alhnelson** [antonio-fiol/tren#4]
Quedaría bien poder identificar la locomotora no sólo por el color sino también con una imagen incluida en el círculo utilizado para su control.

**Comment by antonio-fiol** [comment]
¿Algo así?
![image](https://cloud.githubusercontent.com/assets/23309681/24074153/65b986da-0c03-11e7-8536-7b4c77c42af5.png)

**Comment by antonio-fiol** [comment]
La foto, aunque se ve redonda, es cuadrada, y captura eventos del ratón. En particular, se lleva buena parte de la bola.
