### ISSUE TITLE
Compatibilizar variable minimo

### ISSUE THREAD

**Issue by alhnelson** [antonio-fiol/tren#5]
Para compatibilizar la variable mínimo y evitar el cálculo de la proporción propongo, siempre que sea posible y no suponga mucho trabajo:
añadir un condicionante al programa que:
                    if minimo<100 then minimo=minimo*41
Con ello seguirán funcionando los valores que ya tenemos y también podremos introducir directamente el valor que indica el marcador.

**Comment by antonio-fiol** [comment]
Me pregunto si existirá alguna locomotora que se mueva con menos de 100/4096. Eso invalidaría este enfoque.
Por otra parte, no sería nada complicado, y quizá es incluso más intuititvo, poner un parámetro adicional (porcentaje_minimo por ejemplo), que en lugar de ir de 0 a 4095 vaya de 0 a 100.
¿Cómo lo ves @alhnelson ?
