### ISSUE TITLE
Botón salida círculo velocidad

### ISSUE THREAD

**Issue by alhnelson** [antonio-fiol/tren#7]
El botón de salida en el círculo que indicamos la velocidad resulta demasiado pequeño para la tablet. Hay que darle muchas veces y al estar muy cerca del borde del círculo algunas veces en lugar de salir pone el tren a 80 de velocidad.

**Comment by antonio-fiol** [comment]
Miraré cómo hacer que pueda arrastrarse hacia el lado.

2017-03-23 8:59 GMT+01:00 alhnelson <notifications@github.com>:

**Comment by alhnelson** [comment]
No creo que sea necesario complicarlo demasiado. Si se pudiera mover el mismo botón 3 o 4 pixels a la derecha ya bastaría.
