### ISSUE TITLE
Tiempo de retardo en un sonido después de un evento.

### ISSUE THREAD

**Issue by alhnelson** [antonio-fiol/tren#9]
SonidoEstacion("Salida inmediata del tren {tren.clase} con destino {destino}.").cuando(Estacion.EventoTrenParado),retardo=5.0 .si_activo_para_tren(por_defecto=False)

El tema es que al alargar los tiempos de parada en la estación queda feo que se anuncie la próxima salida justo en el momento de llegar. No se si es factible establecer un retardo configurable en el .py para este evento

**Comment by antonio-fiol** [comment]
Vale, pero la sintaxis sería algo como:
`.cuando(Estacion.EventoTrenParado).`**`tras(5.0)`**`.si_activo_para_tren(por_defecto=False)`
